version: '3'
services:
  mysql:
    image: mysql:8
    container_name: gallery-mysql-production
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: gallery
      MYSQL_ROOT_HOST: '%'
  app:
    image: gallery:latest
    container_name: gallery-app-production
    restart: always
    environment:
      JWT_SECRET: jWtEeV2k19
      ADMIN_EMAIL: admin@ev.cloud
      ADMIN_PASSWORD: EVpw13$$41$$57$$40$$
      UPLOAD_DIR: public/uploads
      PUBLIC_UPLOAD_URL: /uploads
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASS: toor
      NODE_OPTIONS: --max-old-space-size=2048
    links:
      - mysql
    ports:
      - 127.0.0.1:8082:8082
    volumes:
      - ./public/uploads:/app/public/uploads