version: '3'
services:
  mysql:
    image: mysql:8
    container_name: gallery-mysql-production
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: gallery
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3306